name: Zip folder on release

on:
  release:
    types: [published]

jobs:
  zip-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Zip specific folder
        run: |
          FOLDER_TO_ZIP="my-folder"
          ZIP_NAME="${FOLDER_TO_ZIP}.zip"
          zip -r "$ZIP_NAME" "$FOLDER_TO_ZIP"

      - name: Push zip to latest-zip-release branch
        run: |
          BRANCH="latest-zip-release"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create or switch to branch
          git fetch origin $BRANCH || true
          git checkout -B $BRANCH

          # Move the zip into branch root
          mv "${FOLDER_TO_ZIP}.zip" .

          git add "${FOLDER_TO_ZIP}.zip"
          git commit -m "Update zip for $FOLDER_TO_ZIP on release $GITHUB_REF_NAME" || echo "No changes to commit"

          git push origin $BRANCH --force
