name: Create Zip Archive

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: nodenium_custom_models_s13.zip
          path: . 
          exclusions: "*.git* /*node_modules/*" 

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: nodenium_custom_models_s13.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
